### ISSUE TITLE
Spring Boot 1.3 is not working with MongoDB

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/java-buildpack-auto-reconfiguration#50]
It's because of a bug in the connectors: https://github.com/spring-cloud/spring-cloud-connectors/issues/129

**Comment by cgfrost** [comment]
Spring Cloud Connectors is due for a 1.2 release any day. Hopefully spring-cloud/spring-cloud-connectors#129 will make it in and I will spin a release of auto-reconfiguration straight after.

**Comment by cgfrost** [comment]
FYI https://www.pivotaltracker.com/story/show/99609966

**Comment by dsyer** [comment]
Connectors 1.2 is out now. Can this be fixed? How would I know when PWS is using the fix?

**Comment by cgfrost** [comment]
When you push an application you can see it downloading dependencies on the console out put. Keep an eye open for auto reconfiguration version 1.8.0. If you are using offline buildpacks you will have to wait for another release of the buildpack and then another week for PWS to pick that up. That will next happen around the end of August but no guarantees.

**Comment by nebhale** [comment]
Resolved at some point in the past.
