### ISSUE TITLE
New Release of spring-data-mongodb available

### ISSUE THREAD

**Issue by uid09552** [cloudfoundry/java-buildpack-auto-reconfiguration#51]
Hi All,

there is a new release of spring-data-mongodb (1.8.x), which uses the new mongdb drivers (2.13).
MongoDB 3.0 will use SCRAM-SHA1 instead of MONGODB-CR, unfortunately it doesn´t work well with the older drivers (2.12).

Do you have Timeplan for updating the spring-data-mongodb.
Thanks.

BR
Max H.

**Comment by nebhale** [comment]
We don't package `spring-data-mongodb` in the auto-reconfiguration (depending on applications to provide it), but we will test against the latest versions to ensure that we don't break anything.  That can be tracked at https://www.pivotaltracker.com/story/show/109194330.
