### ISSUE TITLE
Support disabling of Play DB Reconfiguration

### ISSUE THREAD

**Issue by nob13** [cloudfoundry/java-buildpack-auto-reconfiguration#52]
Right now Play DB Reconfiguration enables DB Evolutions on all databases found by some parsing of the application.conf. 

However it would be nice if it could be disabled, as having many CF instances doing a race condition in updating a production DB is not always a wise idea. For us it's better to update it by hand or by a single special instance only.

Thanks, Norbert

**Comment by nebhale** [comment]
As the auto-reconfiguration support has lagged for Play releases without any real request for keeping up with it, the forth coming 2.x line will drop all support for Play auto-reconfiguration.
