### ISSUE TITLE
Does not work with Play Slick

### ISSUE THREAD

**Issue by dkowis** [cloudfoundry/java-buildpack-auto-reconfiguration#55]
Certainly doesn't work with play-slick.

I do not get any configuration parameters that I can reference to configure slick.

https://www.playframework.com/documentation/2.5.x/Deploying-CloudFoundry#Connecting-to-Cloud-Foundry-Services That seems to indicate it should be very easy to use, it super doesn't work. :(

**Comment by dkowis** [comment]
Fixed by #57, which I left open.

**Comment by nebhale** [comment]
As the auto-reconfiguration support has lagged for Play releases without any real request for keeping up with it, the forth coming 2.x line will drop all support for Play auto-reconfiguration.

**Comment by dkowis** [comment]
Yep, I understand :(
