### ISSUE TITLE
DB2 / dashDB fancy passwords are not well supported

### ISSUE THREAD

**Issue by bluemixgarage** [cloudfoundry/java-buildpack-auto-reconfiguration#60]
If the dashDB password contains characters such as `@` or `{`, an Invalid URI exception is thrown on WebSphere Liberty at startup.

**Comment by nebhale** [comment]
Can you give an example of the error message you're seeing here?  I'd guess this might be a parsing issue with Spring Cloud Connectors, but without more information it'll be difficult to diagnose.

/cc @scottfrederick

**Comment by scottfrederick** [comment]
Likely related to https://github.com/spring-cloud/spring-cloud-connectors/issues/213.

**Comment by nebhale** [comment]
Agreed.  Just saw it while admiring my PR 😉
