### ISSUE TITLE
Log Warning: Skipping reconfiguration because cloud services already configured

### ISSUE THREAD

**Issue by svenfrauen** [cloudfoundry/java-buildpack-auto-reconfiguration#65]
Hi,

I am getting a warning log message "Skipping reconfiguration because cloud services already configured" which is cause by this code line: https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/blob/master/src/main/java/org/cloudfoundry/reconfiguration/CloudServiceReconfigurationBeanFactoryPostProcessor.java#L53

The reconfiguration of my cloud services is probably skipped as I declared my own Configuration class from AbstractCloudConfig with my own Bean implementation of a ConnectionFactory for RabbitMQ.

Do I have to to do something to get rid of this warning (e.g. turn off auto reconfiguration). Or is this log message a developer information and might be better handled as logger.info or similar level.
As I am using a warning/error logging tool this warning pops up as an issue for me.

Thanks for your help,
Sven

**Comment by nebhale** [comment]
Yep, this should be at `.info()`.  It appears to have gotten an [unintentional upgrade](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration/blob/1.x/auto-reconfiguration/src/main/java/org/cloudfoundry/reconfiguration/spring/AbstractCloudServiceBeanFactoryPostProcessor.java#L59) during the latest round of refactoring.
