### ISSUE TITLE
Spring Auto reconfiguration does not work on CF

### ISSUE THREAD

**Issue by veeraraghavan** [cloudfoundry/java-buildpack-auto-reconfiguration#71]
I am trying to deploy a spring boot application to CF connecting a Postgres backing service . I can see the db properties are not being replaced in run time with VCAP env.  
          I am using the dependency - spring-boot-starter-jdbc ( not spring-boot-starter-data-jpa as i intend to use JDBC template and not JPA).  

**Steps**  

- Added the following jars in pom.xml ( spring-boot-starter-data-jpa , postgresql- driver)

- Create a bean returning the type DataSource

- Specify connection properties in application.properties.  
  
 With this the local setup works fine . When the application is deployed to Cloud foundry the expectation is spring auto reconfiguration should replace the bean with properties in vcap . However the values dont seem to be replaced and system tries to connect to localhost on CF which fails.

**Comment by scottfrederick** [comment]
> I can see the db properties are not being replaced in run time with VCAP env.
> When the application is deployed to Cloud foundry the expectation is spring auto reconfiguration should replace the bean with properties in vcap.

@veeraraghavan I'm not sure I completely understand your expectation. I'll explain how to Java buildpack auto-reconfig works to see if that matches what you're expecting. 

When auto-reconfig detects that a service [of a supported `Service Type`](https://github.com/cloudfoundry/java-buildpack-auto-reconfiguration#what-is-auto-reconfiguration) is bound to the app and that a bean of a matching `Bean Type` exists in the app context, then it will create a new bean of that type using the service binding info in `VCAP_SERVICES` and replace the bean in the app context. It will not replace or override any Spring Boot properties in the Spring `Environment` or add any new property sources to the `Environment`. Replacing the bean in the app context causes Spring Boot autoconfig to back off, and any Boot properties in `application.properties` or `application.yml` relating to connection configuration are ignored. 

You might want to take a look at the new [Java CFEnv library](https://github.com/pivotal-cf/java-cfenv), which is an alternative way to configure connections from bound service credentials. This lib simply maps `VCAP_SERVICES` information to Spring Boot properties, leaving all the connection bean creation to Boot autoconfiguration.

**Comment by veeraraghavan** [comment]
@scottfrederick : Thanks for the explanation. I tried using the spring cloud connector as per the [SO](https://stackoverflow.com/questions/56571077/spring-boot-auto-reconfiguration-not-working-on-spring-boot-data-starter-jdbc/56584763#56584763) and also looked up the samples from [link](https://github.com/cloudfoundry-samples/hello-spring-cloud)
I still have questions about how to make DB connection work locally as well as in cf (currently in the sample the db name is never specified anywhere within the app).
However since SO is a place to discuss questions and there is no issue with auto reconfiguration i am closing the issue
