### ISSUE TITLE
Connecting to a Redis Cluster

### ISSUE THREAD

**Issue by AnirKulk** [cloudfoundry/java-buildpack-auto-reconfiguration#77]
Is there an example which shows how the RedisConnectionFactory maybe be auto reconfigured such that it is able to connect to a Redis Cluster?

**Comment by AnirKulk** [comment]
Can someone please comment on this issue? My observation is that the auto reconfig mechanism always initializes the LettuceConnectionFactory instance using the default constructor, but instead I want it to use the overloaded constructor that takes RedisClusterConfiguration as a constructor argument.

**Comment by scottfrederick** [comment]
Auto-reconfiguration is designed to handle very simple cases of wiring Spring applications to bound services. It does not support more advanced configuration or customization of the configuration. 

If you application is using Spring Boot, you should look into the [starter library](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#boot-features-redis) provided by Boot and the [properties](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#data-properties) that can be used to configure the connection, and use the [Java CFEnv](https://github.com/pivotal-cf/java-cfenv) library to automatically populate Boot properties from bound services.

**Comment by AnirKulk** [comment]
Thank you @scottfrederick.
