### ISSUE TITLE
spring-data-mongodb > 3.0 not compatible

### ISSUE THREAD

**Issue by oliveti** [cloudfoundry/java-buildpack-auto-reconfiguration#78]
According to java buildpack documentation (here : https://docs.cloudfoundry.org/buildpacks/java/configuring-service-connections/spring-service-bindings.html#mongodb) auto configuration happen in that case : Auto-reconfiguration occurs if Cloud Foundry detects an `org.springframework.data.document.mongodb.MongoDbFactory`

But, since spring-data-mongodb 3.0 `MongoDbFactory` is deprecated, `MongoDatabaseFactory` is used instead.

In result, there is no `MongoDbFactory` bean to reconfigure and connection fails in java application with these kind of errors : 

`Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}`
`com.mongodb.MongoSocketOpenException: Exception opening socket`

Is that a known issue ? Are there plans to support spring-data-mongodb > 3.0 ?

**Comment by scottfrederick** [comment]
This is related to #74. As discussed in that issue, the Spring Cloud Connectors library that is used to implement Java buildpack auto-reconfiguration is in [maintenance mode](https://github.com/spring-cloud/spring-cloud-connectors#spring-cloud-connectors-). Supporting `spring-data-mongodb` 3.0 would require major changes to Spring Cloud Connectors, which we won't do for reasons discussed in [this issue](https://github.com/spring-cloud/spring-cloud-connectors/issues/314). 

As a work-around until there is a resolution to #74, you can add the Java CFEnv library to your application and disable Java buildpack auto-reconfiguration as shown in the [project documentation](https://github.com/pivotal-cf/java-cfenv#using-spring-boot).

**Comment by dmikusa-pivotal** [comment]
Thanks @scottfrederick +1 to that

**Comment by oliveti** [comment]
Hello,

Thank you a lot for your detailed answer, sounds good and we will go with include Java CFEnv as a workaround for now.
